services:

  backend:
    image: vishalhe123/backend:${IMAGE_TAG}
    container_name: user_backend
    ports:
      - "3000:3000"

  web:
    image: vishalhe123/web:${IMAGE_TAG}
    container_name: user_web
    ports:
      - "3001:3001"

  ws-server:
    image: vishalhe123/ws-server:${IMAGE_TAG}
    container_name: user_ws
    ports:
      - "4000:4000"