FROM oven/bun:1

WORKDIR /usr/src/app
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server

COPY . .
RUN bun install --registry https://registry.npmjs.org
RUN bun run db:generate
EXPOSE 3000
CMD ["bun","run","start:backend"]
