FROM oven/bun:latest

WORKDIR /app

COPY . .

RUN bun install --frozen-lockfile

RUN bunx prisma generate --schema=packages/db/prisma/schema.prisma

WORKDIR /app/apps/web

RUN bun run build

EXPOSE 3001

CMD ["bun", "run", "start"]