FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
# Copy package.json files needed for workspace dependencies
COPY apps/http-server/package.json ./apps/http-server/package.json
COPY packages/db/package.json ./packages/db/package.json

RUN bun install --frozen-lockfile

COPY apps/http-server ./apps/http-server
COPY packages/db ./packages/db

RUN bunx prisma generate --schema=packages/db/prisma/schema.prisma
WORKDIR /app/apps/http-server
EXPOSE 3000
CMD ["bun","index.ts"]